signing:
    key: 345345fsdfsf5345
spring:
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        driver-class-name: org.postgresql.Driver
        password: '{cipher}ac7e20c69aeb008fa289f7d6ce78fbdcef7625ade9d3b278fd4a05f1b282e89e'
        platform: postgres
        testWhileIdle: true
        url: jdbc:postgresql://localhost:5432/eagle_eye
        username: postgres
        validationQuery: SELECT 1
    jpa:
        database: POSTGRESQL
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
# jce下载的是java8 password和username一样